/* eslint-disable quotes */
const ERROR_CODE = {
  // Route Error
  URL_NOT_FOUND: 'URL_NOT_FOUND',

  // Auth Errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_FOUND_OR_ALREADY_USED: 'NOT_FOUND_OR_ALREADY_USED',
  NOT_FOUND_OR_ALREADY_VERIFIED: 'NOT_FOUND_OR_ALREADY_VERIFIED',
  BAD_TOKEN: 'BAD_TOKEN',
  DISABLED_ACCOUNT: 'DISABLED_ACCOUNT',

  // General Errors
  NOT_FOUND: 'NOT_FOUND',
  ID_MALFORMED: 'ID_MALFORMED',

  // Input Errors
  MISSING: 'MISSING',
  IS_EMPTY: 'IS_EMPTY',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  STORE_ALREADY_EXISTS: 'STORE_ALREADY_EXISTS',
  CONFIG_ALREADY_EXISTS: 'CONFIG_ALREADY_EXISTS',
  AGGREGATOR_ALREADY_EXISTS: 'AGGREGATOR_ALREADY_EXISTS',
  EMAIL_IS_NOT_VALID: 'EMAIL_IS_NOT_VALID',
  INVALID_ROLE: 'INVALID_ROLE',
  INVALID_AGGREGATOR_ID: 'INVALID_AGGREGATOR_ID',
  INVALID_AGGREGATOR_NAME: 'INVALID_AGGREGATOR_NAME',
  INVALID_STORE_ID: 'INVALID_STORE_ID',
  INVALID_STORE_NAME: 'INVALID_STORE_NAME',
  INVALID_HOST: 'INVALID_HOST',
  MUST_BE_BOOLEAN: 'Must be a boolean true or false',
  MUST_BE_NUMBER: 'INALID NUMBER',
  AT_LEAST_ONE_FIELD_REQUIRED: 'AT_LEAST_ONE_FIELD_REQUIRED',
  MUST_BE_ARRAY: 'Must be an array',
  MUST_BE_NON_EMPTY_ARRAY: 'Must be a non-empty array',
  INVALID_ACTION: 'Action is invalid',
  ISACTIVE_REQUIRED: 'isActive field is required for action UPDATE',
  INVALID_OOSTHRESHOLD: 'INVALID_OOSTHRESHOLD',
  VALUE_MUST_BE_GREATER_THAN_ZERO: 'VALUE_MUST_BE_GREATER_THAN_ZERO',
  END_DATE_MUST_BE_AFTER_START_DATE: 'END_DATE_MUST_BE_AFTER_START_DATE',
  INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
  INVALID_VALUE: 'INVALID_VALUE',
  DUPLICATE_DATA: 'Duplicate Value Found',
  INVALID_CRON_EXPRESSION: 'INVALID_CRON_EXPRESSION',
  INVALID_PAGE: 'Page number must be a positive integer',
  LAST_UPDATED_REQUIRED: 'Last updated date is required',

  // Password Error
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT_MIN_5',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  INVALID_PASSWORD_FORMAT: 'Invalid password format',
}

export { ERROR_CODE }
